AOS.init({ duration: 1000, once: true, offset: 100 });
const services = [{ icon: 'fa-scissors', title: 'Haircut & Styling', description: 'Professional cuts and styling for all hair types', price: '$45-$120' }, { icon: 'fa-brush', title: 'Hair Coloring', description: 'Premium color treatments and highlights', price: '$80-$200' }, { icon: 'fa-hand-sparkles', title: 'Manicure & Pedicure', description: 'Luxurious nail care and design', price: '$30-$55' }, { icon: 'fa-wand-magic-sparkles', title: 'Makeup', description: 'Professional makeup for any occasion', price: '$60-$150' }];
const gallery = [{ img: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80' }, { img: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80' }, { img: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&q=80' }, { img: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600&q=80' }, { img: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&q=80' }, { img: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&q=80' }];
const team = [{ name: 'Emma Wilson', specialty: 'Hair Stylist', image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&q=80' }, { name: 'Sofia Martinez', specialty: 'Makeup Artist', image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80' }, { name: 'Olivia Chen', specialty: 'Nail Specialist', image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80' }];
const servicesGrid = document.getElementById('servicesGrid');
services.forEach((service, i) => { const card = document.createElement('div'); card.className = 'service-card'; card.setAttribute('data-aos', 'fade-up'); card.setAttribute('data-aos-delay', i * 100); card.innerHTML = `<div class="service-icon"><i class="fa-solid ${service.icon}"></i></div><h3>${service.title}</h3><p>${service.description}</p><div class="service-price">${service.price}</div>`; servicesGrid.appendChild(card) });
const galleryGrid = document.getElementById('galleryGrid');
gallery.forEach((item, i) => { const div = document.createElement('div'); div.className = 'gallery-item'; div.setAttribute('data-aos', 'zoom-in'); div.setAttribute('data-aos-delay', i * 100); div.innerHTML = `<img src="${item.img}" alt="Gallery">`; galleryGrid.appendChild(div) });
const teamGrid = document.getElementById('teamGrid');
team.forEach((member, i) => { const card = document.createElement('div'); card.className = 'team-card'; card.setAttribute('data-aos', 'fade-up'); card.setAttribute('data-aos-delay', i * 100); card.innerHTML = `<div class="team-image"><img src="${member.image}" alt="${member.name}"></div><div class="team-info"><h3>${member.name}</h3><div class="team-specialty">${member.specialty}</div></div>`; teamGrid.appendChild(card) });
function showBookingModal() { document.getElementById('bookingModal').classList.add('active') }
function closeBookingModal() { document.getElementById('bookingModal').classList.remove('active') }
function handleBooking(e) { e.preventDefault(); showNotification('Booking confirmed!'); setTimeout(closeBookingModal, 1500) }
document.getElementById('bookingModal').addEventListener('click', (e) => { if (e.target.id === 'bookingModal') closeBookingModal() });
function showNotification(message) { const notification = document.createElement('div'); notification.style.cssText = 'position:fixed;top:100px;right:30px;background:linear-gradient(135deg,#B76E79,#E8A5A5);color:white;padding:1.25rem 2.5rem;border-radius:50px;box-shadow:0 10px 40px rgba(183,110,121,0.4);z-index:10000;font-weight:700;animation:slideIn 0.5s ease-out'; notification.innerHTML = `<i class="fas fa-check-circle" style="margin-right:0.65rem"></i>${message}`; document.body.appendChild(notification); setTimeout(() => { notification.style.animation = 'slideOut 0.5s ease-out'; setTimeout(() => notification.remove(), 500) }, 2500) }
const style = document.createElement('style'); style.textContent = '@keyframes slideIn{from{transform:translateX(500px);opacity:0}to{transform:translateX(0);opacity:1}}@keyframes slideOut{from{transform:translateX(0);opacity:1}to{transform:translateX(500px);opacity:0}}'; document.head.appendChild(style);
console.log('💇 Glamour Salon loaded successfully!');
