AOS.init({ duration: 1000, once: true, offset: 100 });
const services = [{ icon: 'fa-heart-pulse', color: '#ef4444', title: 'Cardiology', description: 'Expert cardiac care with state-of-the-art diagnostics and treatment for all heart conditions.' }, { icon: 'fa-baby', color: '#8b5cf6', title: 'Pediatrics', description: 'Specialized healthcare for infants, children and adolescents with compassionate care.' }, { icon: 'fa-bone', color: '#f59e0b', title: 'Orthopedics', description: 'Advanced treatment for bone, joint and muscle conditions with minimally invasive procedures.' }, { icon: 'fa-brain', color: '#10b981', title: 'Neurology', description: 'Comprehensive neurological care for brain and nervous system disorders.' }, { icon: 'fa-scissors', color: '#06b6d4', title: 'Surgery', description: 'Expert surgical procedures using cutting-edge technology and techniques.' }, { icon: 'fa-x-ray', color: '#6366f1', title: 'Radiology', description: 'Advanced imaging and diagnostic services for accurate medical assessments.' }];
const doctors = [{ name: 'Dr. Sarah Johnson', specialty: 'Cardiology', experience: '15 years', image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&q=80' }, { name: 'Dr. Michael Chen', specialty: 'Neurology', experience: '12 years', image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80' }, { name: 'Dr. Emily Rodriguez', specialty: 'Pediatrics', experience: '10 years', image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&q=80' }, { name: 'Dr. James Wilson', specialty: 'Orthopedics', experience: '18 years', image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&q=80' }];
const servicesGrid = document.getElementById('servicesGrid');
services.forEach((service, i) => { const card = document.createElement('div'); card.className = 'service-card'; card.setAttribute('data-aos', 'fade-up'); card.setAttribute('data-aos-delay', i * 100); card.innerHTML = `<div class="service-icon" style="background:${service.color}"><i class="fa-solid ${service.icon}"></i></div><h3>${service.title}</h3><p>${service.description}</p>`; servicesGrid.appendChild(card) });
const doctorsGrid = document.getElementById('doctorsGrid');
doctors.forEach((doctor, i) => { const card = document.createElement('div'); card.className = 'doctor-card'; card.setAttribute('data-aos', 'fade-up'); card.setAttribute('data-aos-delay', i * 100); card.innerHTML = `<div class="doctor-image"><img src="${doctor.image}" alt="${doctor.name}"><div class="doctor-overlay"><button class="btn-primary" onclick="showAppointmentModal()"><span>Book Appointment</span></button></div></div><div class="doctor-info"><h3>${doctor.name}</h3><div class="specialty">${doctor.specialty}</div><div class="experience">${doctor.experience} experience</div></div>`; doctorsGrid.appendChild(card) });
function animateCounter(el) { const target = parseInt(el.dataset.count); let count = 0; const increment = target / 60; const timer = setInterval(() => { count += increment; if (count >= target) { el.textContent = target + (target === 24 ? '/7' : '+'); clearInterval(timer) } else { el.textContent = Math.floor(count) + (target === 24 ? '' : '+'); } }, 30) }
document.querySelectorAll('.stat-number').forEach(animateCounter);
function showAppointmentModal() { document.getElementById('appointmentModal').classList.add('active') }
function closeAppointmentModal() { document.getElementById('appointmentModal').classList.remove('active') }
function handleAppointment(e) { e.preventDefault(); showNotification('Appointment booked successfully!'); setTimeout(closeAppointmentModal, 1500) }
function callEmergency() { showNotification('Calling Emergency: 911'); setTimeout(() => { window.location.href = 'tel:911' }, 1000) }
document.getElementById('emergencyBtn').addEventListener('click', callEmergency);
document.getElementById('appointmentModal').addEventListener('click', (e) => { if (e.target.id === 'appointmentModal') closeAppointmentModal() });
function showNotification(message) { const notification = document.createElement('div'); notification.style.cssText = `position:fixed;top:100px;right:30px;background:linear-gradient(135deg,#10b981,#059669);color:white;padding:1.25rem 2.5rem;border-radius:50px;box-shadow:0 10px 40px rgba(16,185,129,0.4);z-index:10000;font-weight:700;animation:slideIn 0.5s ease-out`; notification.innerHTML = `<i class="fas fa-check-circle" style="margin-right:0.65rem"></i>${message}`; document.body.appendChild(notification); setTimeout(() => { notification.style.animation = 'slideOut 0.5s ease-out'; setTimeout(() => notification.remove(), 500) }, 2500) }
const style = document.createElement('style'); style.textContent = '@keyframes slideIn{from{transform:translateX(500px);opacity:0}to{transform:translateX(0);opacity:1}}@keyframes slideOut{from{transform:translateX(0);opacity:1}to{transform:translateX(500px);opacity:0}}'; document.head.appendChild(style);
console.log('🏥 MediCare Hospital loaded successfully!');
